package config

import "github.com/Mengbooo/BemoNews/server/internal/model"

func DefaultSources() []model.SourceConfig {
	return []model.SourceConfig{
		{
			ID:               "openai-blog",
			Name:             "OpenAI Blog",
			Type:             model.ConnectorRSS,
			URL:              "https://openai.com/news/rss.xml",
			Category:         model.GroupOfficialBlog,
			Enabled:          true,
			Priority:         10,
			FetchIntervalMin: 60,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "anthropic-news",
			Name:             "Anthropic News",
			Type:             model.ConnectorRSS,
			URL:              "https://www.anthropic.com/news/rss.xml",
			Category:         model.GroupOfficialBlog,
			Enabled:          true,
			Priority:         10,
			FetchIntervalMin: 60,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "deepmind-blog",
			Name:             "Google DeepMind Blog",
			Type:             model.ConnectorRSS,
			URL:              "https://deepmind.google/blog/rss.xml",
			Category:         model.GroupOfficialBlog,
			Enabled:          true,
			Priority:         9,
			FetchIntervalMin: 60,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "huggingface-blog",
			Name:             "Hugging Face Blog",
			Type:             model.ConnectorRSS,
			URL:              "https://huggingface.co/blog/feed.xml",
			Category:         model.GroupOfficialBlog,
			Enabled:          true,
			Priority:         8,
			FetchIntervalMin: 120,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "arxiv-cs-ai",
			Name:             "arXiv cs.AI",
			Type:             model.ConnectorAPI,
			URL:              "https://export.arxiv.org/api/query?search_query=cat:cs.AI&sortBy=submittedDate&sortOrder=descending&max_results=25",
			Category:         model.GroupResearch,
			Enabled:          true,
			Priority:         8,
			FetchIntervalMin: 180,
			TimeWindowHours:  72,
			ParserType:       "arxiv",
		},
		{
			ID:               "arxiv-cs-lg",
			Name:             "arXiv cs.LG",
			Type:             model.ConnectorAPI,
			URL:              "https://export.arxiv.org/api/query?search_query=cat:cs.LG&sortBy=submittedDate&sortOrder=descending&max_results=25",
			Category:         model.GroupResearch,
			Enabled:          true,
			Priority:         7,
			FetchIntervalMin: 180,
			TimeWindowHours:  72,
			ParserType:       "arxiv",
		},
		{
			ID:               "arxiv-cs-cl",
			Name:             "arXiv cs.CL",
			Type:             model.ConnectorAPI,
			URL:              "https://export.arxiv.org/api/query?search_query=cat:cs.CL&sortBy=submittedDate&sortOrder=descending&max_results=25",
			Category:         model.GroupResearch,
			Enabled:          true,
			Priority:         7,
			FetchIntervalMin: 180,
			TimeWindowHours:  72,
			ParserType:       "arxiv",
		},
		{
			ID:               "github-engineering",
			Name:             "GitHub Engineering",
			Type:             model.ConnectorRSS,
			URL:              "https://github.blog/engineering/feed/",
			Category:         model.GroupEngineering,
			Enabled:          true,
			Priority:         8,
			FetchIntervalMin: 120,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "anthropic-engineering",
			Name:             "Anthropic Engineering",
			Type:             model.ConnectorRSS,
			URL:              "https://www.anthropic.com/engineering/rss.xml",
			Category:         model.GroupEngineering,
			Enabled:          true,
			Priority:         8,
			FetchIntervalMin: 120,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "openai-engineering",
			Name:             "OpenAI Engineering",
			Type:             model.ConnectorRSS,
			URL:              "https://openai.com/index/openai-engineering/rss.xml",
			Category:         model.GroupEngineering,
			Enabled:          true,
			Priority:         8,
			FetchIntervalMin: 120,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "cursor-blog",
			Name:             "Cursor Blog",
			Type:             model.ConnectorRSS,
			URL:              "https://cursor.com/blog/rss.xml",
			Category:         model.GroupEngineering,
			Enabled:          true,
			Priority:         7,
			FetchIntervalMin: 120,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "hacker-news",
			Name:             "Hacker News",
			Type:             model.ConnectorAPI,
			URL:              "https://hn.algolia.com/api/v1/search_by_date?tags=story&hitsPerPage=30",
			Category:         model.GroupCommunity,
			Enabled:          true,
			Priority:         9,
			FetchIntervalMin: 30,
			TimeWindowHours:  48,
			ParserType:       "hn",
		},
		{
			ID:               "github-trending",
			Name:             "GitHub Trending",
			Type:             model.ConnectorAPI,
			URL:              "https://api.github.com/search/repositories?q=created:%3E2026-01-01&sort=stars&order=desc&per_page=25",
			Category:         model.GroupCommunity,
			Enabled:          true,
			Priority:         7,
			FetchIntervalMin: 120,
			TimeWindowHours:  72,
			ParserType:       "github",
		},
		{
			ID:               "mit-technology-review-ai",
			Name:             "MIT Technology Review AI",
			Type:             model.ConnectorRSS,
			URL:              "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
			Category:         model.GroupMedia,
			Enabled:          true,
			Priority:         7,
			FetchIntervalMin: 90,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "techcrunch-ai",
			Name:             "TechCrunch AI",
			Type:             model.ConnectorRSS,
			URL:              "https://techcrunch.com/category/artificial-intelligence/feed/",
			Category:         model.GroupMedia,
			Enabled:          true,
			Priority:         7,
			FetchIntervalMin: 90,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "the-verge-ai",
			Name:             "The Verge AI",
			Type:             model.ConnectorRSS,
			URL:              "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
			Category:         model.GroupMedia,
			Enabled:          true,
			Priority:         6,
			FetchIntervalMin: 90,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "venturebeat-ai",
			Name:             "VentureBeat AI",
			Type:             model.ConnectorRSS,
			URL:              "https://venturebeat.com/ai/feed/",
			Category:         model.GroupMedia,
			Enabled:          true,
			Priority:         6,
			FetchIntervalMin: 90,
			TimeWindowHours:  48,
			ParserType:       "generic-rss",
		},
		{
			ID:               "import-ai",
			Name:             "Import AI",
			Type:             model.ConnectorRSS,
			URL:              "https://importai.substack.com/feed",
			Category:         model.GroupNewsletter,
			Enabled:          true,
			Priority:         6,
			FetchIntervalMin: 180,
			TimeWindowHours:  72,
			ParserType:       "generic-rss",
		},
		{
			ID:               "the-batch",
			Name:             "The Batch",
			Type:             model.ConnectorRSS,
			URL:              "https://www.deeplearning.ai/the-batch/feed/",
			Category:         model.GroupNewsletter,
			Enabled:          true,
			Priority:         6,
			FetchIntervalMin: 180,
			TimeWindowHours:  72,
			ParserType:       "generic-rss",
		},
		{
			ID:               "tldr-ai",
			Name:             "TLDR AI",
			Type:             model.ConnectorRSS,
			URL:              "https://tldr.tech/ai/rss",
			Category:         model.GroupNewsletter,
			Enabled:          true,
			Priority:         5,
			FetchIntervalMin: 180,
			TimeWindowHours:  72,
			ParserType:       "generic-rss",
		},
	}
}
