package processing

import (
	"context"
	"fmt"
	"slices"
	"time"

	"github.com/Mengbooo/BemoNews/server/internal/model"
	"github.com/Mengbooo/BemoNews/server/internal/store"
)

type Orchestrator struct {
	store store.Store
}

func NewOrchestrator(dataStore store.Store) *Orchestrator {
	return &Orchestrator{store: dataStore}
}

func (o *Orchestrator) Run(_ context.Context, date string, fetchRunID string) (*model.ProcessingRun, error) {
	startedAt := time.Now().UTC()
	items, err := o.store.GetCollectedItems(date)
	if err != nil {
		return nil, err
	}

	topics := buildTopics(items)
	if err := o.store.SaveTopics(date, topics); err != nil {
		return nil, err
	}

	quickDraft := buildBriefDraft(date, model.BriefQuick, topics)
	quickDraft.ProcessingRunID = runID("processing")
	fullDraft := buildBriefDraft(date, model.BriefFull, topics)
	fullDraft.ProcessingRunID = quickDraft.ProcessingRunID

	if err := o.store.SaveBriefDraft(quickDraft); err != nil {
		return nil, err
	}
	if err := o.store.SaveBriefDraft(fullDraft); err != nil {
		return nil, err
	}

	manifest, err := o.store.GetManifest()
	if err != nil {
		return nil, err
	}

	upsertManifestEntry(manifest, model.ManifestEntry{
		Date:        date,
		Type:        quickDraft.Type,
		Title:       quickDraft.Title,
		GeneratedAt: quickDraft.GeneratedAt,
		Stats:       quickDraft.Stats,
	})
	upsertManifestEntry(manifest, model.ManifestEntry{
		Date:        date,
		Type:        fullDraft.Type,
		Title:       fullDraft.Title,
		GeneratedAt: fullDraft.GeneratedAt,
		Stats:       fullDraft.Stats,
	})

	if err := o.store.SaveManifest(*manifest); err != nil {
		return nil, err
	}

	run := model.ProcessingRun{
		ID:               quickDraft.ProcessingRunID,
		FetchRunID:       fetchRunID,
		Date:             date,
		Status:           "success",
		StartedAt:        startedAt,
		EndedAt:          time.Now().UTC(),
		InputItems:       len(items),
		TopicCount:       len(topics),
		QuickBriefID:     quickDraft.ID,
		FullBriefID:      fullDraft.ID,
		CrossSourceCount: countCrossSourceTopics(topics),
	}

	if err := o.store.SaveProcessingRun(run); err != nil {
		return nil, err
	}

	return &run, nil
}

func buildTopics(items []model.CollectedItem) []model.ProcessedTopic {
	topics := make([]model.ProcessedTopic, 0, len(items))
	for index, item := range items {
		topic := model.ProcessedTopic{
			ID:                     fmt.Sprintf("topic-%d-%d", time.Now().UTC().UnixNano(), index),
			Title:                  item.Title,
			CanonicalURL:           item.CanonicalURL,
			Summary:                item.Summary,
			SourceIDs:              []string{item.SourceID},
			ItemIDs:                []string{item.ID},
			PrimaryCategory:        item.Category,
			Tags:                   []string{string(item.Category)},
			PublishedAt:            item.PublishedAt,
			Importance:             model.ImportanceMedium,
			NoveltyScore:           0.5,
			CredibilityScore:       0.5,
			RichnessScore:          0.5,
			DuplicateGroupSize:     1,
			IsCrossSourceConfirmed: false,
			Status:                 "ready",
		}
		topics = append(topics, topic)
	}

	return topics
}

func buildBriefDraft(date string, briefType model.BriefType, topics []model.ProcessedTopic) model.BriefDraft {
	topicIDs := make([]string, 0, len(topics))
	crossSourceTopics := 0
	for _, topic := range topics {
		topicIDs = append(topicIDs, topic.ID)
		if topic.IsCrossSourceConfirmed {
			crossSourceTopics++
		}
	}

	title := fmt.Sprintf("bemoNews %s brief · %s", briefLabel(briefType), date)
	summary := "Scaffold draft generated by the core pipeline. Topic shaping and layout rules can build on top of this payload."
	sections := buildSections(briefType, topicIDs)

	draft := model.BriefDraft{
		ID:          fmt.Sprintf("brief-%s-%s", date, briefType),
		Type:        briefType,
		Date:        date,
		Title:       title,
		Summary:     summary,
		GeneratedAt: time.Now().UTC(),
		TopicIDs:    topicIDs,
		Sections:    sections,
		Stats: model.BriefStats{
			InputItems:        len(topics),
			SelectedTopics:    len(topicIDs),
			DroppedItems:      0,
			CrossSourceTopics: crossSourceTopics,
		},
	}

	if len(topicIDs) > 0 {
		draft.LeadTopicID = topicIDs[0]
	}

	return draft
}

func buildSections(briefType model.BriefType, topicIDs []string) []model.BriefDraftSection {
	switch briefType {
	case model.BriefQuick:
		return []model.BriefDraftSection{
			{Key: "executive-snapshot", Title: "Executive Snapshot", TopicIDs: slices.Clone(firstN(topicIDs, 4))},
			{Key: "top-brief", Title: "Top Brief", TopicIDs: slices.Clone(firstN(topicIDs, 4))},
			{Key: "decision-signals", Title: "Decision Signals", TopicIDs: slices.Clone(firstN(topicIDs, 3))},
			{Key: "watchlist", Title: "Watchlist", TopicIDs: slices.Clone(firstN(topicIDs, 4))},
		}
	default:
		return []model.BriefDraftSection{
			{Key: "top-stories", Title: "Top Stories", TopicIDs: slices.Clone(firstN(topicIDs, 6))},
			{Key: "trending-discussions", Title: "Trending Discussions", TopicIDs: slices.Clone(firstN(topicIDs, 6))},
			{Key: "community-picks", Title: "Community Picks", TopicIDs: slices.Clone(firstN(topicIDs, 4))},
			{Key: "industry-research", Title: "Industry & Research", TopicIDs: slices.Clone(firstN(topicIDs, 6))},
			{Key: "new-tools", Title: "New Tools", TopicIDs: slices.Clone(firstN(topicIDs, 4))},
			{Key: "curated-resources", Title: "Curated Resources", TopicIDs: slices.Clone(firstN(topicIDs, 8))},
			{Key: "open-source", Title: "Open Source & Tools", TopicIDs: slices.Clone(firstN(topicIDs, 6))},
		}
	}
}

func briefLabel(briefType model.BriefType) string {
	if briefType == model.BriefQuick {
		return "quick"
	}
	return "full"
}

func upsertManifestEntry(manifest *model.Manifest, entry model.ManifestEntry) {
	for index, existing := range manifest.Briefs {
		if existing.Date == entry.Date && existing.Type == entry.Type {
			manifest.Briefs[index] = entry
			return
		}
	}
	manifest.Briefs = append(manifest.Briefs, entry)
}

func countCrossSourceTopics(topics []model.ProcessedTopic) int {
	count := 0
	for _, topic := range topics {
		if topic.IsCrossSourceConfirmed {
			count++
		}
	}
	return count
}

func firstN(items []string, limit int) []string {
	if len(items) <= limit {
		return items
	}
	return items[:limit]
}

func runID(prefix string) string {
	return fmt.Sprintf("%s-%d", prefix, time.Now().UTC().UnixNano())
}
